
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install
                command: npm install
            - run:
                name: Run unit tests
                command: npm run test
            - run:
                name: Trigger reload
                command: curl -X POST -d {} "${WEBHOOK_URL}?token=${WEBHOOK_TOKEN}"

workflows:
    build-and-test:
      jobs:
        - build-and-test
